run:
  tests: false
  skip-files:
    - "_minimock.go$"

linters-settings:
  funlen:
    lines: 150
    statements: 80

linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - gomnd
    - lll
    - nakedret
    - testpackage
    - wsl
    - nestif
    - gosec